#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run lint-staged ||
(
    echo 'Prettier Format Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me... 🤔🤔🤔🤔'

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'